version: 1.0.{build}
os: Visual Studio 2017
skip_tags: true
configuration: Release

environment:
  sonarqubetoken:
    secure: ppdeirHI9dsM7NpQgtwIRqXbiqhJZvIyHxOFhnME5HhRFS6IbYZqRppQi7fTqv37

before_build:
  - ps: .\scripts\set-version.ps1
  - cmd: dotnet --info
  - cmd: dotnet restore
  - choco install opencover.portable
  - choco install codecov
  - choco install xunit
  - choco install "msbuild-sonarqube-runner" -y
  - choco install 7zip

build_script:
  - SonarScanner.MSBuild.exe begin /k:"DeveVipAccess" /o:"devedse-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=%sonarqubetoken% /d:sonar.cs.opencover.reportsPaths=".\DeveVipAccess.Coverage.xml" /d:sonar.coverage.exclusions="DeveVipAccess.ConsoleApp/**/*.cs,DeveVipAccess.Tests/**/*.cs"
  - cmd: dotnet build -c Release
  - OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"test .\DeveVipAccess.Tests\DeveVipAccess.Tests.csproj -c Release" -oldstyle -returntargetcode -output:.\DeveVipAccess.Coverage.xml -filter:"+[DeveVipAccess*]*"
  - SonarScanner.MSBuild.exe end /d:sonar.login=%sonarqubetoken%
  - codecov -f "DeveVipAccess.Coverage.xml"

#test_script:
#  - cmd: dotnet test -c release DeveVipAccess.Tests\DeveVipAccess.Tests.csproj
  
after_test:
  - cmd: dotnet pack -c Release DeveVipAccess\
  - ps: Scripts\GoPackage.ps1
  - cmd: dotnet publish DeveVipAccess.ConsoleApp -r win-x64 -c Release --self-contained
  - ps: Scripts\GoPackage_ConsoleApp.ps1
  - cmd: dotnet publish DeveVipAccess.ConsoleApp -r win-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true

artifacts:
- path: Scripts\Output\DeveVipAccess.7z
  name: droppackage7z
- path: Scripts\Output\DeveVipAccess.zip
  name: droppackagezip
- path: Scripts\Output\DeveVipAccess.ConsoleApp.7z
  name: DeveVipAccessConsoleApp7z
- path: Scripts\Output\DeveVipAccess.ConsoleApp.zip
  name: DeveVipAccessConsoleAppzip
- path: DeveVipAccess.ConsoleApp\bin\Release\netcoreapp3.0\win-x64\publish\DeveVipAccess.ConsoleApp.exe
  name: DeveVipAccessConsoleApp
- path: 'DeveVipAccess\bin\Release\*.nupkg'
  name: nugetPackages

deploy:
- provider: GitHub
  auth_token:
    secure: do7S++r1rE5E3IZujCoMONsWYJNF7eoRoPyJbxSD851I850OlEq0gsHH/Tji7o00
  artifact: droppackage7z,droppackagezip,nugetPackages
- provider: NuGet
  api_key:
    secure: pVOzQthQbu7P9SUQwjG43ZEMcwAp7dVbe4BkDVEwJFu1gWK+L11L9mdfGLC5iO5Z
  skip_symbols: true
  artifact: /.*\.nupkg/
